# Generated by Django 4.1.7 on 2023-03-29 20:09

import blocks.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_flexpage_body_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(help_text='Richly formatted text', icon='doc-full', label='Rich Text')), ('title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Title to display', max_length=100, required=True))])), ('header', wagtail.blocks.StructBlock([('header', wagtail.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header Size')), ('text', wagtail.blocks.CharBlock(label='Text', max_length=50))])), ('table', blocks.blocks.TableBlock()), ('typed_table', wagtail.contrib.typed_table_block.blocks.TypedTableBlock([('text', wagtail.blocks.CharBlock(help_text='Plain text cell')), ('rich_text', wagtail.blocks.RichTextBlock(help_text='Rich text cell')), ('numeric', wagtail.blocks.FloatBlock(help_text='Numeric cell')), ('integer', wagtail.blocks.IntegerBlock(help_text='Integer cell')), ('page', wagtail.blocks.PageChooserBlock(help_text='Page within the site'))])), ('block_quote', blocks.blocks.BlockQuoteBlock()), ('image_text_overlay', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('text', wagtail.blocks.CharBlock(label='Text', max_length=200))])), ('list_with_images', wagtail.blocks.StructBlock([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('title', wagtail.blocks.CharBlock(label='Title', max_length=200)), ('text', wagtail.blocks.CharBlock(label='Text', max_length=200)), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=200, required=False)), ('link_url', wagtail.blocks.URLBlock(label='Link URL', max_length=200, required=False))]), label='List Item'))])), ('thumbnail_gallery', wagtail.blocks.StructBlock([('image_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))]), label='Image'))])), ('raw_html', wagtail.blocks.RawHTMLBlock(help_text='Raw HTML (use with care)'))], blank=True, null=True, use_json_field=True),
        ),
    ]
