# Generated by Django 4.1.11 on 2023-09-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('content', '0006_captchaemailform_emailform_emailformfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDEExplorerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Name of this common data element', max_length=100)),
                ('definition', models.TextField(blank=True, help_text='A thorough definition of this CDE')),
                ('required', models.CharField(blank=True, help_text='Required, not, or something else?', max_length=50)),
                ('data_type', models.CharField(blank=True, help_text='Kind of data', max_length=30)),
                ('explanatory_note', models.TextField(blank=True, help_text='Note helping explain use of the CDE')),
                ('inheritance', models.BooleanField(default=False, help_text='Attribute inherits values')),
            ],
        ),
        migrations.CreateModel(
            name='CDEExplorerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('spreadsheet_id', models.CharField(blank=True, help_text='Optional file ID of a Google Drive spreadsheet', max_length=250)),
                ('update_log', models.TextField(blank=True, help_text='Log of how well the last update went')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CDEPermissibleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='An enumerated value allowed for a data element that uses permissible values', max_length=200)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissible_values', to='content.cdeexplorerattribute')),
            ],
        ),
        migrations.CreateModel(
            name='CDEExplorerObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this object in a CDE hierarchy', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A nice long description of this object')),
                ('stewardship', models.TextField(blank=True, help_text="Who's responsible for this object")),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_objects', to='content.cdeexplorerpage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.cdeexplorerobject')),
            ],
        ),
        migrations.AddField(
            model_name='cdeexplorerattribute',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='content.cdeexplorerobject'),
        ),
    ]
