# Generated by Django 4.2.20 on 2025-03-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("content", "0007_cdeexplorerattribute_cdeexplorerpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostmanAPIPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("postman", models.TextField(help_text="Postman JSON Export")),
                ("swagger", models.TextField(help_text="OpenAPI YAML Conversion")),
                (
                    "postmanerator",
                    models.TextField(
                        blank=True,
                        help_text="Postmanerator documentation using EDRN Portal Theme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
