# Generated by Django 4.2.20 on 2025-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_postmanapipage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmanapipage",
            name="postmanerator",
            field=models.TextField(
                blank=True,
                help_text="Postmanerator documentation using NIST Help Theme",
            ),
        ),
    ]
