# Generated by Django 4.1.7 on 2023-03-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_manager', models.CharField(blank=True, help_text='Name of the site manager', max_length=60)),
                ('webmaster', models.CharField(blank=True, help_text='Name of the webmaster', max_length=60)),
                ('clearance', models.CharField(blank=True, help_text='Clearance №', max_length=20)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
