# Generated by Django 4.1.13 on 2023-12-01 19:42

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("nistauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetpage",
            name="preamble",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Introductory text to appear above the form"
            ),
        ),
    ]
