# Generated by Django 4.1.7 on 2023-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('h', 'Header'), ('b', 'Bottom')], default='b', help_text='Where to inject this; in the <head> or at the bottom before the closing </body>', max_length=1)),
                ('code', models.TextField(default='<script></script>', help_text='JavaScript analytics code')),
            ],
        ),
    ]
